# -*- coding: utf-8 -*-
"""reviewradarfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FCW7E4vggqvZd3z9SbPae_UzwWO2xy6
"""


from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY")
)

import pandas as pd

df = pd.read_csv(
    "Amazon_Reviews.csv",
    encoding='latin1',
    engine='python',
    on_bad_lines='skip'
)

print("Columns:", df.columns)

reviews = df["Review Text"].dropna().astype(str).tolist()

# Limit for speed (change later)
# reviews = reviews[:500]

print("Loaded:", len(reviews))

from sentence_transformers import SentenceTransformer
from transformers import pipeline

# Semantic model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Sentiment model
sentiment_model = pipeline("sentiment-analysis",model="distilbert-base-uncased-finetuned-sst-2-english")

def openrouter_summary(text):
    response = client.chat.completions.create(
        model="meta-llama/llama-3-8b-instruct",
        messages=[
            {
                "role": "system",
                "content": "You analyze customer reviews and extract key insights."
            },
            {
                "role": "user",
                "content": f"""
Analyze these reviews and give 3 clear bullet points of the main issues:

{text}
"""
            }
        ]
    )

    return response.choices[0].message.content

import numpy as np



import faiss

review_embeddings = np.load("embeddings.npy")
index = faiss.read_index("faiss.index")


print("✅ System Ready")

#checking if entire dataset is processed (reviews count, embedding count, and FAISS index size all match)

def search_and_summarize(query, k=15):
    query_embedding = model.encode([query])
    D, I = index.search(query_embedding, k)

    

    output = f"🔍 Query: {query}\n\nTop Results:\n\n" 
    collected_text = ""

    # Detect query intent (positive/negative)
    target_sentiment = sentiment_model(query)[0]['label']

    count = 0

    for idx in I[0]:
        text = reviews[idx]

        # Get sentiment
        sentiment = sentiment_model(text[:512])[0]['label']

        if target_sentiment is None or sentiment == target_sentiment:
            output += f"[{sentiment}] {text}\n\n"
            collected_text += text + " "
            count += 1

        if count >= 5:
            break

    # -------------------------------
    # SUMMARY (DistilBART - best free)
    # -------------------------------
    if collected_text:
        summary = openrouter_summary(collected_text[:2000])
        output += "\nSummary:\n" + summary
    return output


